version: '3.7'

services:
  elements-mock:
    image: elements-mock
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./source:/usr/src/app/source