version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t netmilk/element-mock .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push netmilk/element-mock
